apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ServiceName }}
spec:
  selector:
    app: {{ .Values.selector }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
      