apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.mysql.name }}
spec:
  selector:
    app: {{ .Values.selector.mysql.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.mysql.port }}
      targetPort: {{ .Values.service.mysql.targetPort }}
      