deployment:
  image: mysql
  tag: latest
  name: mysql
  replica: 2

selector: mysql-db

replicas: 1

container:
  mysql:
    portNumber: 3306

secret: mysql-secret

config: mysql-config

servicePort: 3306
ServiceName: mysql-svc


# ingress: helm-ingress